<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="h_lower_limb">
	  <xacro:arg name="scale" default="0.5"/>
	  <xacro:arg name="enableGzPlugin" default="false"/>
	  <xacro:property name="radius" value="${0.25*$(arg scale)}"/>
    <xacro:property name="offset" value="${radius*2.5}"/>
  <link
    name="chaser/base_link">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="1" />
      <inertia
        ixx="1"
        ixy="0"
        ixz="0"
        iyy="1"
        iyz="0"
        izz="1" />
    </inertial>
    <collision>
      <origin
        xyz="0 0 ${offset}"
        rpy="0 0 3.1415"/>
      <geometry>
        <mesh
          filename="package://foot_control_xy/models/h_lower_limb/meshes/foot.dae" scale="${0.05*$(arg scale)} ${0.05*$(arg scale)} ${0.05*$(arg scale)}"/>
      </geometry>
    </collision>
    <visual>
      <origin
        xyz="0 0 ${offset}"
        rpy="0 0 3.1415"/>
      <geometry>
        <mesh
          filename="package://foot_control_xy/models/h_lower_limb/meshes/foot.dae" scale="${0.05*$(arg scale)} ${0.05*$(arg scale)} ${0.05*$(arg scale)}"/>
      </geometry>
    </visual>
  </link> 
    <xacro:if value="$(arg enableGzPlugin)">
	  <gazebo>
	   <plugin name="gzTfUpdate" filename="libgzTfUpdate.so">
			<actorName>chaser</actorName>
	   </plugin>
	  </gazebo>
  </xacro:if>
</robot>
