<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="target_plane_on_table">
  <xacro:arg name="origin.x" default="0"/>
  <xacro:arg name="origin.y" default="0"/>
  <xacro:arg name="origin.z" default="0"/>
  <xacro:arg name="enableGzPlugin" default="true"/>   
  <xacro:arg name="scale" default="0.15"/>
  <xacro:property name="toolMass" value="0.1"/>
  <xacro:property name="toolLength" value="0.40"/>
  <xacro:property name="toolRadius" value="0.005"/>
  <xacro:property name="tableLength" value="2"/>
  <xacro:property name="tableWidth" value="2"/>
  <xacro:property name="tableHeight" value="1"/>

  <link name="world"/>

  <gazebo reference="world">
    <static>true</static>
    <turnGravityOff>true</turnGravityOff>
  </gazebo>

  <xacro:include filename="$(find surgical_simulator)/models/table.urdf.xacro"/>

  <xacro:model_table name="table"
                    parent="world"
                    length="${tableLength}"
                    width="${tableWidth}"
                    height="${tableHeight}"
                    plate_thickness="0.1"
                    color="grey">
    <origin xyz="${$(arg origin.x)-tableLength/2} ${$(arg origin.y)+tableWidth/2} ${tableHeight}" rpy="0 0 0"/>
  </xacro:model_table>

  <gazebo reference="table_plate_link">
   <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="table_leg_0_link">
   <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="table_leg_1_link">
   <material>Gazebo/Blue</material>
  </gazebo>
  
  <gazebo reference="table_leg_2_link">
   <material>Gazebo/Blue</material>
  </gazebo>
  
  <gazebo reference="table_leg_3_link">
   <material>Gazebo/Blue</material>
  </gazebo>
    

  <joint name="target_table_joint" type="fixed">
    <origin xyz="${tableLength/2} ${-tableWidth/2} 0" rpy="0 0 0"/>
    <parent link="table_plate_link"/>
    <child link="target/base_link"/>
  </joint>

  <link name="target/base_link">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="1" />
      <inertia
        ixx="1"
        ixy="0"
        ixz="0"
        iyy="1"
        iyz="0"
        izz="1" />
    </inertial>
<!--     <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://foot_control_xy/models/target/meshes/target.dae" scale="$(arg scale) $(arg scale) ${0.000001*$(arg scale)}"/>  
      </geometry>
    </collision> -->
    <visual name="visual">
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
            filename="package://foot_control_xy/models/target/meshes/target.dae" scale="$(arg scale) $(arg scale) ${0.001*$(arg scale)}"/>
       </geometry>
      </visual>
  </link>
</robot>
