<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="number1">  
	<xacro:arg name="enableGzPlugin" default="true"/>		
  <xacro:arg name="scale" default="0.15"/>
  <xacro:property name="radius" value="${0.25*$(arg scale)}"/>
  <link
    name="target/base_link">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="1" />
      <inertia
        ixx="1"
        ixy="0"
        ixz="0"
        iyy="1"
        iyz="0"
        izz="1" />
    </inertial>
    <!--collision>
      <origin
        xyz="0 0 ${2*_radius}"
        rpy="0 0 0" />
      <geometry>
        <box size="${_radius} ${_radius} ${_radius}"/>
      </geometry>
    </collision-->
      <visual name="visual">
		<origin
		xyz="0 0 ${2*radius}"
        rpy="0 0 -1.5707963267" />
        <geometry>
          <mesh
            filename="package://foot_control_xy/models/number1/meshes/number.dae" scale="$(arg scale) $(arg scale) $(arg scale)"/>
        </geometry>
      </visual>
  </link>
    <xacro:if value="$(arg enableGzPlugin)">
	   <gazebo>
	   <plugin name="gzTfUpdate" filename="libgzTfUpdate.so">
			<actorName>target</actorName>
	   </plugin>
	  </gazebo>
  </xacro:if>
</robot>

