set(_CATKIN_CURRENT_PACKAGE "foot_control_xy")
set(foot_control_xy_VERSION "1.0.0")
set(foot_control_xy_MAINTAINER "walid <walid.amanhoud@epfl.ch>, jacob <jacob.hernandez@epfl.ch>, jacob <anais.haget@epfl.ch>")
set(foot_control_xy_PACKAGE_FORMAT "1")
set(foot_control_xy_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "dynamic_reconfigure" "tf")
set(foot_control_xy_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "dynamic_reconfigure" "tf")
set(foot_control_xy_BUILDTOOL_DEPENDS "catkin")
set(foot_control_xy_BUILDTOOL_EXPORT_DEPENDS )
set(foot_control_xy_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "dynamic_reconfigure" "tf")
set(foot_control_xy_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "dynamic_reconfigure" "tf")
set(foot_control_xy_TEST_DEPENDS )
set(foot_control_xy_DOC_DEPENDS )
set(foot_control_xy_URL_WEBSITE "")
set(foot_control_xy_URL_BUGTRACKER "")
set(foot_control_xy_URL_REPOSITORY "")
set(foot_control_xy_DEPRECATED "")